const express = require('express')

module.exports = express.Router()
  .use('/settings', require('./settings'))
  .use('/fileSystemTree', require('./fileSystemTree'))
  .use('/contentModel', require('./contentModel'))
  .use('/collections', require('./collections'))
  .use('/categories', require('./categories'))
  .use('/category', require('./category'))
  .use('/posts', require('./posts'))
  .use('/post', require('./post'))
  .use('/subpages', require('./subpages'))
  .use('/subpage', require('./subpage'))
  .use('/homepage', require('./homepage'))
  .use('/tags', require('./tags'))
  .use('/tag', require('./tag'))
  .use('/ssg', require('./ssg'))
  .use('/ssgOptions', require('./ssgOptions'))
  .use('/workspace', require('./workspace'))
