const express = require('express')

module.exports = express.Router()
  .use('/settings', require('./settings'))
  .use('/fileSystemTree', require('./fileSystemTree'))
  .use('/contentModel', require('./contentModel'))
  .use('/contentTypes', require('./contentTypes'))
  .use('/collections', require('./collections'))
  .use('/subpages', require('./subpages'))
  .use('/subpage', require('./subpage'))
  .use('/homepage', require('./homepage'))
  .use('/ssg', require('./ssg'))
  .use('/ssgOptions', require('./ssgOptions'))
  .use('/workspace', require('./workspace'))
