const express = require('express')

module.exports = (state) => express.Router()
  .use('/category', require('./category')(state))
  .use('/collections', require('./collections')(state))
  .use('/contentModel', require('./contentModel'))
  .use('/contentTypes', require('./contentTypes')(state))
  .use('/fileSystemTree', require('./fileSystemTree'))
  .use('/homepage', require('./homepage')(state))
  .use('/post', require('./post')(state))
  .use('/settings', require('./settings'))
  .use('/ssg', require('./ssg'))
  .use('/ssgOptions', require('./ssgOptions')(state))
  .use('/subpage', require('./subpage')(state))
  .use('/subpages', require('./subpages'))
  .use('/workspace', require('./workspace'))
