#!/usr/bin/env node
const writ = require('../')
const manual = require('./manual')
const Flag = require('./flag')

const cli = process.argv.slice(2)

if (!cli.length) {
  console.log(manual)
  process.exit(1)
}

let [ mode, ...opts ] = cli

const modes = ['start', 'build']
const flags = {
  refreshTheme: new Flag('refresh-theme', 'r'),
  debug: new Flag('debug', 'd')
}

if (!modes.includes(mode)) {
  console.log('Incorrect usage, see manual:\n' + manual)
  process.exit(1)
}

const options = {
  rootDirectory: opts.find(Flag.isNotFlag) || '.',
  refreshTheme: flags.refreshTheme.test(opts),
  debug: flags.debug.test(opts),
  cli: true
}

if (options.debug) {
  console.log('cli', { mode, opts, options })
}

writ[mode](options)
