#!/usr/bin/env node
const ssg = require('../ssg')
const createCMS = require('../cms')
const manual = require('./manual')
const Flag = require('./flag')

const cli = process.argv.slice(2)

if (!cli.length) {
  console.log(manual)
  process.exit(1)
}

let [ mode, ...opts ] = cli

const modes = ['start', 'build', 'create']
const flags = {
  refreshTheme: new Flag('refresh-theme', 'r'),
  debug: new Flag('debug', 'd')
}

if (!modes.includes(mode)) {
  console.log('Incorrect usage, see manual:\n' + manual)
  process.exit(1)
}

const options = {
  rootDirectory: opts.find(Flag.isNotFlag) || '.',
  refreshTheme: flags.refreshTheme.test(opts),
  debug: flags.debug.test(opts),
  cli: true
}

if (options.debug) {
  console.log('cli', { mode, opts, options })
}

if (mode === 'start') {
  const cms = createCMS({
    ssgOptions: {
      rootDirectory: options.rootDirectory,
      refreshTheme: options.refreshTheme,
      debug: options.debug,
      cli: true
    }
  })
  cms.server.start({
    silent: false
  })
} else if (mode === 'create') {
  const cms = createCMS()
  cms.server.start({
    silent: false
  })
} else {
  ssg.build(options)
}
