#!/usr/bin/env node

const writ = require('../')
const manual = require('./manual')

const cli = process.argv.slice(2)

if (!cli.length) {
  console.log(manual)
  process.exit(1)
}

let [ mode, rootDirectory, debug ] = cli

if (mode !== 'start' && mode !== 'build') {
  console.log('Incorrect usage, see manual:\n' + manual)
  process.exit(1)
}

const DEBUG_FLAG = /(--|)debug/
const secondParameterIsDebug = rootDirectory?.match(DEBUG_FLAG)
if (!rootDirectory || secondParameterIsDebug) {
  rootDirectory = '.'
}

const debugMode = !!(debug?.match(DEBUG_FLAG) || secondParameterIsDebug)

if (secondParameterIsDebug && debug) {
  console.log('Incorrect usage, see manual:\n' + manual)
  process.exit(1)
}

writ[mode]({
  rootDirectory,
  debug: debugMode
})
